package config

const (
	WRITE_ERROR              = "寫入失敗"
	VERIFY_ERROR             = "驗證失敗"
	SIGNIN_ERROR             = "登入失敗"
	SIGNIN_SUCCESS           = "登入成功"
	NOT_SIGNIN               = "未登入"
	SIGNUP_ERROR             = "註冊失敗"
	SIGNUP_SUCCESS           = "註冊成功"
	WRITE_FILE_ERROR         = "寫入檔案失敗"
	ARGS_ERROR               = "參數錯誤"
	CREATE_SUCCESS           = "新增成功"
	UPDATE_SUCCESS           = "修改成功"
	DELETE_IMG_ERROR         = "刪除圖檔出錯"
	DELETE_ERROR             = "刪除失敗"
	DELETE_SUCCESS           = "刪除成功"
	NOT_FOUND_IMAGE_FOLDER   = "沒有image資料夾"
	NOT_FOUND_IMAGE          = "找不到圖片"
	RENAME_ERROR             = "重新命名錯誤"
	NOT_FOUND_DATA_ERROR     = "找不到任何資訊"
	REQUEST_DATA_ERROR       = "資料回傳錯誤"
	EXEC_SUCCESS             = "執行正常"
	CONTINUE_NOT_FOUND_IMAGE = "圖片沒有找到,仍繼續執行"
	SQL_WRITE_ERROR          = "SQL寫入異常"
	SQL_QUERY_ERROR          = "SQL查詢異常"
	ADD_IMAGE_ERROR          = "新增圖片異常"
	NOT_FOUND_PRODUCT_ERROR  = "找不到商品"
)
